{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "provider-argocd.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/portforward
  - services
  - services/finalizers
  - endpoints
  - events
  - configmaps
  - secrets
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocd.projectkerberus.io
  resources:
  - tokens
  - tokens/status
  - providerconfigs
  - providerconfigs/status
  - providerconfigusages
  - providerconfigusages/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}